apiVersion: v1
kind: Service
metadata:
  name: my-rds-service
  namespace: default
spec:
  type: ExternalName
  externalName: database-1.cv2wiwiqkto9.us-east-1.rds.amazonaws.com  # Replace with your RDS endpoint
